export type QuestionPreset = {
  question_text: string
  text_option_a: string
  text_option_b: string
}

export const QUESTION_BANK: Record<'easy' | 'medium' | 'hard', QuestionPreset[]> = {
  easy: [
    { question_text: '¿Playa o montaña?',                    text_option_a: 'Playa 🏖️',              text_option_b: 'Montaña 🏔️' },
    { question_text: '¿Pizza o hamburguesa?',                text_option_a: 'Pizza 🍕',               text_option_b: 'Hamburguesa 🍔' },
    { question_text: '¿Perros o gatos?',                     text_option_a: 'Perros 🐶',              text_option_b: 'Gatos 🐱' },
    { question_text: '¿Verano o invierno?',                  text_option_a: 'Verano ☀️',              text_option_b: 'Invierno ❄️' },
    { question_text: '¿Café o té?',                          text_option_a: 'Café ☕',                text_option_b: 'Té 🍵' },
    { question_text: '¿Netflix en casa o cine?',             text_option_a: 'Netflix en casa 🛋️',    text_option_b: 'Cine 🎬' },
    { question_text: '¿Madrugador o noctámbulo?',            text_option_a: 'Madrugador 🌅',          text_option_b: 'Noctámbulo 🌙' },
    { question_text: '¿Dulce o salado?',                     text_option_a: 'Dulce 🍫',               text_option_b: 'Salado 🍟' },
    { question_text: '¿Ciudad o naturaleza?',                text_option_a: 'Ciudad 🏙️',             text_option_b: 'Naturaleza 🌿' },
    { question_text: '¿Libro o serie?',                      text_option_a: 'Libro 📚',               text_option_b: 'Serie 📺' },
    { question_text: '¿Música o silencio al trabajar?',      text_option_a: 'Música 🎵',              text_option_b: 'Silencio 🤫' },
    { question_text: '¿WhatsApp o llamada?',                 text_option_a: 'WhatsApp ✉️',            text_option_b: 'Llamada 📞' },
    { question_text: '¿Coche o transporte público?',         text_option_a: 'Coche 🚗',               text_option_b: 'Transporte público 🚇' },
    { question_text: '¿Cocinar o pedir comida?',             text_option_a: 'Cocinar 🍳',             text_option_b: 'Pedir comida 📦' },
    { question_text: '¿Ropa cómoda o elegante?',             text_option_a: 'Cómoda 👕',              text_option_b: 'Elegante 👔' },
    { question_text: '¿Quedarse en casa o salir?',           text_option_a: 'Quedarse en casa 🏠',    text_option_b: 'Salir 🎉' },
    { question_text: '¿Instagram o TikTok?',                 text_option_a: 'Instagram 📸',           text_option_b: 'TikTok 🎵' },
    { question_text: '¿Hotel o apartamento?',                text_option_a: 'Hotel 🏨',               text_option_b: 'Apartamento 🏡' },
    { question_text: '¿Gym o deporte al aire libre?',        text_option_a: 'Gym 🏋️',                text_option_b: 'Aire libre 🌳' },
    { question_text: '¿Ahorrar o vivir el momento?',         text_option_a: 'Ahorrar 💰',             text_option_b: 'Vivir el momento 🎯' },
    { question_text: '¿Desayuno en casa o fuera?',           text_option_a: 'En casa 🏠',             text_option_b: 'En un café ☕' },
    { question_text: '¿Lluvia o sol?',                       text_option_a: 'Lluvia 🌧️',             text_option_b: 'Sol ☀️' },
    { question_text: '¿Ducha por la mañana o por la noche?', text_option_a: 'Por la mañana 🌅',       text_option_b: 'Por la noche 🌙' },
    { question_text: '¿Mesa o sofá para comer?',             text_option_a: 'Mesa 🪑',                text_option_b: 'Sofá 🛋️' },
    { question_text: '¿Peli de acción o romántica?',         text_option_a: 'Acción 💥',              text_option_b: 'Romántica ❤️' },
    { question_text: '¿Comprar online o en tienda?',         text_option_a: 'Online 🛒',              text_option_b: 'Tienda física 🏪' },
    { question_text: '¿Beber agua o refresco?',              text_option_a: 'Agua 💧',                text_option_b: 'Refresco 🥤' },
    { question_text: '¿Fútbol o baloncesto?',                text_option_a: 'Fútbol ⚽',              text_option_b: 'Baloncesto 🏀' },
    { question_text: '¿Series de drama o comedia?',          text_option_a: 'Drama 😢',               text_option_b: 'Comedia 😂' },
    { question_text: '¿Podcast o música?',                   text_option_a: 'Podcast 🎙️',            text_option_b: 'Música 🎵' },
    { question_text: '¿Fotos o vídeos?',                     text_option_a: 'Fotos 📷',               text_option_b: 'Vídeos 🎥' },
    { question_text: '¿Lunes o viernes?',                    text_option_a: 'Lunes 💼',               text_option_b: 'Viernes 🎉' },
    { question_text: '¿Cerveza o vino?',                     text_option_a: 'Cerveza 🍺',             text_option_b: 'Vino 🍷' },
    { question_text: '¿Tapas o plato único?',                text_option_a: 'Tapas 🍤',               text_option_b: 'Plato único 🍛' },
    { question_text: '¿Calor o frío?',                       text_option_a: 'Calor 🌞',               text_option_b: 'Frío 🧤' },
    { question_text: '¿Aventura o relajación?',              text_option_a: 'Aventura 🧗',            text_option_b: 'Relajación 🏖️' },
    { question_text: '¿Viaje de mochila o resort?',          text_option_a: 'Mochila 🎒',             text_option_b: 'Resort 🏨' },
    { question_text: '¿Cumpleaños íntimo o gran fiesta?',    text_option_a: 'Íntimo 🕯️',             text_option_b: 'Gran fiesta 🎂' },
    { question_text: '¿Primavera o otoño?',                  text_option_a: 'Primavera 🌸',           text_option_b: 'Otoño 🍂' },
    { question_text: '¿Reunión presencial o videollamada?',  text_option_a: 'Presencial 🤝',          text_option_b: 'Videollamada 💻' },
    { question_text: '¿Tatuajes o sin tatuajes?',            text_option_a: 'Con tatuajes 🖊️',       text_option_b: 'Sin tatuajes ✨' },
    { question_text: '¿Madrugar a correr o yoga en casa?',   text_option_a: 'Correr 🏃',              text_option_b: 'Yoga 🧘' },
    { question_text: '¿Cocinar para otros o que te cocinen?',text_option_a: 'Cocinar para otros 👨‍🍳', text_option_b: 'Que me cocinen 🍽️' },
    { question_text: '¿Música en directo o en streaming?',   text_option_a: 'Directo 🎸',             text_option_b: 'Streaming 🎧' },
    { question_text: '¿Levantarte con alarma o sin?',        text_option_a: 'Con alarma ⏰',          text_option_b: 'Sin alarma 😴' },
    { question_text: '¿Vacaciones en Europa o fuera?',       text_option_a: 'Europa 🏛️',             text_option_b: 'Fuera de Europa ✈️' },
    { question_text: '¿Pagar en efectivo o con tarjeta?',    text_option_a: 'Efectivo 💵',            text_option_b: 'Tarjeta 💳' },
    { question_text: '¿Pedir el menú o à la carte?',         text_option_a: 'Menú del día 📋',        text_option_b: 'À la carte 🍽️' },
    { question_text: '¿Pintura o música como hobby?',        text_option_a: 'Pintura 🎨',             text_option_b: 'Música 🎶' },
    { question_text: '¿Mañana de domingo activa o sin planes?', text_option_a: 'Activa 🌞',           text_option_b: 'Sin planes 😴' },
  ],

  medium: [
    { question_text: '¿Cuál sería tu superpoder?',                  text_option_a: 'Volar ✈️',                         text_option_b: 'Ser invisible 👻' },
    { question_text: '¿Qué valoras más en una pareja?',             text_option_a: 'Pasión ❤️‍🔥',                        text_option_b: 'Estabilidad 🏡' },
    { question_text: '¿Cómo resuelves los conflictos?',             text_option_a: 'Hablo directo 💬',                  text_option_b: 'Dejo pasar el tiempo ⏳' },
    { question_text: '¿Qué haces si te quedas sin batería?',        text_option_a: 'Busco cargador urgente 🔋',          text_option_b: 'Me desconecto y disfruto 🧘' },
    { question_text: '¿Qué tipo de viaje prefieres?',               text_option_a: 'Todo organizado 🗺️',               text_option_b: 'Totalmente improvisado 🎲' },
    { question_text: '¿Cómo te relajas de verdad?',                 text_option_a: 'Solo/a en calma 😌',               text_option_b: 'Con gente y movimiento 🥳' },
    { question_text: '¿A qué miras más?',                           text_option_a: 'Al pasado con nostalgia 🕰️',       text_option_b: 'Al futuro con ilusión 🚀' },
    { question_text: 'Si ganas la lotería, ¿qué haces?',            text_option_a: 'Invierto y ahorro 📈',              text_option_b: 'Me doy un capricho 🛍️' },
    { question_text: '¿Qué rol tienes en un grupo?',                text_option_a: 'Propongo planes 💡',                text_option_b: 'Sigo la corriente 🌊' },
    { question_text: '¿Cómo afrontas los cambios?',                 text_option_a: 'Me adapto fácil 🌀',               text_option_b: 'Prefiero la rutina 🔄' },
    { question_text: '¿Cuál es tu prioridad vital?',                text_option_a: 'Éxito profesional 💼',              text_option_b: 'Vida personal plena 🌸' },
    { question_text: 'En una conversación, ¿eres más...?',          text_option_a: 'El que escucha 👂',                 text_option_b: 'El que habla 🗣️' },
    { question_text: '¿Qué te importa más de una ciudad?',          text_option_a: 'Oferta cultural 🎭',               text_option_b: 'Calidad de vida 🌿' },
    { question_text: '¿Qué prefieres tener?',                       text_option_a: 'Muchos conocidos 👥',               text_option_b: 'Pocos amigos íntimos 💞' },
    { question_text: '¿Cómo tomas decisiones importantes?',         text_option_a: 'Con la razón 🧠',                   text_option_b: 'Con el corazón ❤️' },
    { question_text: '¿Qué prefieres en el trabajo?',               text_option_a: 'Autonomía total 🕊️',               text_option_b: 'Buen equipo 🤝' },
    { question_text: 'Si vivieras en otro siglo, ¿cuándo?',         text_option_a: 'En el pasado 🏰',                   text_option_b: 'En el futuro 🤖' },
    { question_text: '¿Cómo aprendes algo nuevo?',                  text_option_a: 'Leyendo e investigando 📖',          text_option_b: 'Probando y equivocándome 🔧' },
    { question_text: '¿Qué te genera más estrés?',                  text_option_a: 'El caos y el desorden 🌪️',         text_option_b: 'La monotonía y el aburrimiento 😴' },
    { question_text: '¿Con qué frase te identificas?',              text_option_a: '«Menos es más» 🤍',                 text_option_b: '«Más es más» 🎨' },
    { question_text: '¿Qué valoras más en una amistad?',            text_option_a: 'Lealtad 🤝',                        text_option_b: 'Diversión 🎉' },
    { question_text: '¿Cómo celebras tus éxitos?',                  text_option_a: 'En silencio y para mí 🕯️',         text_option_b: 'Compartiéndolo con todos 🥂' },
    { question_text: 'Si te equivocas, ¿qué haces primero?',        text_option_a: 'Pido disculpas 🙏',                 text_option_b: 'Intento justificarme 💬' },
    { question_text: '¿Qué te motiva más?',                         text_option_a: 'El reconocimiento externo 🏆',      text_option_b: 'La satisfacción personal 💫' },
    { question_text: '¿Qué te da más miedo?',                       text_option_a: 'Fracasar 📉',                       text_option_b: 'No haberlo intentado 🚪' },
    { question_text: '¿En qué inviertes más energía?',              text_option_a: 'En mis proyectos 💡',               text_option_b: 'En las personas que quiero 💞' },
    { question_text: '¿Qué te dice más de alguien?',                text_option_a: 'Cómo trata a desconocidos 🌍',      text_option_b: 'Cómo actúa bajo presión 🔥' },
    { question_text: '¿Cuándo te sientes más tú mismo/a?',          text_option_a: 'Cuando estoy solo/a 🧘',            text_option_b: 'Cuando estoy con mis personas 👨‍👩‍👧' },
    { question_text: '¿Qué te resulta más difícil?',                text_option_a: 'Pedir ayuda 🤚',                    text_option_b: 'Decir que no 🚫' },
    { question_text: '¿Qué define el éxito para ti?',               text_option_a: 'Impacto en los demás 🌍',           text_option_b: 'Libertad económica 💰' },
    { question_text: 'Ante una injusticia, ¿qué haces?',            text_option_a: 'Actúo de forma directa ✊',          text_option_b: 'Busco la vía diplomática 🕊️' },
    { question_text: '¿Cómo describes tu ambición?',                text_option_a: 'Quiero ser el mejor en lo mío 🥇',  text_option_b: 'Quiero tener un impacto real 🌱' },
    { question_text: '¿Qué tipo de rutina prefieres?',              text_option_a: 'Estructurada al detalle 📋',         text_option_b: 'Flexible y adaptable 🌀' },
    { question_text: '¿Dónde te inspiras más?',                     text_option_a: 'En la soledad 🌙',                  text_option_b: 'En el contacto con los demás 🤗' },
    { question_text: '¿Qué actitud tienes ante el riesgo?',         text_option_a: 'Calculo bien antes de actuar 🔍',   text_option_b: 'Me lanzo y aprendo 🪂' },
    { question_text: '¿Qué define tu estilo de trabajo?',           text_option_a: 'Perfeccionismo 🔬',                 text_option_b: 'Pragmatismo 🔧' },
    { question_text: '¿Cuándo eres más productivo/a?',              text_option_a: 'Con presión y deadlines 🔥',         text_option_b: 'Con calma y sin urgencia 🌿' },
    { question_text: '¿Cómo manejas la soledad?',                   text_option_a: 'La disfruto y la necesito 🌿',      text_option_b: 'Me pesa y la evito 🏃' },
    { question_text: '¿En qué confías más para decidir?',           text_option_a: 'Los datos y los hechos 📊',          text_option_b: 'La intuición y el instinto 🔮' },
    { question_text: '¿Cómo describes tu relación con el dinero?',  text_option_a: 'Es un medio, no un fin 🧭',          text_option_b: 'Es una medida de libertad 🗝️' },
    { question_text: '¿Qué te cuesta más mantener?',                text_option_a: 'La constancia en mis hábitos 💪',   text_option_b: 'El entusiasmo inicial 🚀' },
    { question_text: '¿Cómo reaccionas a la crítica?',              text_option_a: 'La analizo y aprendo 📖',            text_option_b: 'Me afecta más de lo que quisiera 😔' },
    { question_text: '¿Qué tipo de liderazgo ejerces?',             text_option_a: 'Lidero desde el frente 🦁',          text_option_b: 'Empodero a los demás 🤲' },
    { question_text: '¿Qué buscas en un viaje?',                    text_option_a: 'Conocer culturas nuevas 🌏',         text_option_b: 'Desconectar completamente 🧘' },
    { question_text: '¿Qué te genera más orgullo?',                 text_option_a: 'Lo que he construido 🏗️',           text_option_b: 'La confianza que otros depositan en mí 💙' },
    { question_text: '¿Qué prefieres dar a los demás?',             text_option_a: 'Consejos honestos 🗣️',              text_option_b: 'Apoyo incondicional 🫂' },
    { question_text: '¿Qué parte de ti cambiarías?',                text_option_a: 'Mi forma de relacionarme 🤝',       text_option_b: 'Mi gestión emocional 🌊' },
    { question_text: '¿Qué talento oculto te gustaría tener?',      text_option_a: 'Arte o música 🎨',                  text_option_b: 'Atletismo o deporte 🏅' },
    { question_text: '¿Cómo gestionas el tiempo libre?',            text_option_a: 'Con actividades planificadas 📅',   text_option_b: 'Con improvisación total 🎲' },
    { question_text: '¿Cómo describes tu forma de amar?',           text_option_a: 'Con actos y detalles 🎁',           text_option_b: 'Con palabras y tiempo ⏱️' },
    { question_text: '¿Qué prefieres que digan de ti en el trabajo?',text_option_a: 'Que eres brillante 💡',             text_option_b: 'Que eres imprescindible 🔑' },
  ],

  hard: [
    { question_text: 'Si te dieran 1M€, ¿qué harías primero?',              text_option_a: 'Mataría a alguien y pagaría la multa 🔫',      text_option_b: 'Compraría un piso en Madrid 🏠' },
    { question_text: 'Si supieras que no te pillan, ¿qué harías?',          text_option_a: 'Robar en un banco 🏦',                          text_option_b: 'Hacer trampa en los impuestos 📊' },
    { question_text: '¿Qué preferirías saber?',                             text_option_a: 'La fecha exacta de tu muerte 💀',               text_option_b: 'La forma en que vas a morir ⚰️' },
    { question_text: '¿Qué poder escogerías aunque tenga consecuencias?',   text_option_a: 'Leer la mente de todos 🧠',                     text_option_b: 'Ver el futuro sin poder cambiarlo 🔮' },
    { question_text: 'Si reseteas tu vida, ¿qué cambiarías?',               text_option_a: 'Tu personalidad entera 🎭',                     text_option_b: 'Todas tus relaciones actuales 💔' },
    { question_text: '¿Qué dilema escogerías?',                             text_option_a: 'Ser famoso pero odiado 📺',                     text_option_b: 'Ser anónimo pero muy querido 🤗' },
    { question_text: '¿A qué renunciarías por el éxito?',                   text_option_a: 'A tus amistades actuales 👋',                   text_option_b: 'A diez años de tu vida ⏰' },
    { question_text: '¿Qué prefieres que digan de ti al morir?',            text_option_a: '«Era muy bueno pero aburrido» 😴',              text_option_b: '«Era un caos pero apasionante» 🔥' },
    { question_text: 'Si pudieras borrar un recuerdo, ¿cuál?',              text_option_a: 'El más doloroso 😭',                            text_option_b: 'El más feliz, para revivirlo 😊' },
    { question_text: '¿Cuál sería tu mayor traición posible?',              text_option_a: 'Traicionar a un amigo por dinero 💰',           text_option_b: 'Mentir a tu pareja para protegerla 🤥' },
    { question_text: 'Si vivieras solo 200 años o mueres a los 60...',      text_option_a: 'Vivir 200 años completamente solo 👴',          text_option_b: 'Morir a los 60 muy acompañado 🫂' },
    { question_text: 'Para tener poder, ¿a qué precio?',                    text_option_a: 'Perder tu memoria de infancia 👶',              text_option_b: 'Perder la capacidad de amar ❤️' },
    { question_text: '¿Cuál es el mayor tabú que romperías?',               text_option_a: 'Hablar de dinero en público 💵',                text_option_b: 'Decir tu opinión real sobre todo 🗣️' },
    { question_text: 'Si solo puedes salvar a uno, ¿a quién?',              text_option_a: 'A tu mejor amigo 👫',                           text_option_b: 'A un extraño que salvará 100 vidas 🦸' },
    { question_text: '¿Qué descubrirías si pudieras?',                      text_option_a: 'Si tu pareja te ha sido infiel alguna vez 👀',   text_option_b: 'Lo que piensan de ti tus amigos de verdad 💭' },
    { question_text: 'Si el mundo acaba mañana, ¿qué haces?',               text_option_a: 'Se lo cuento a todo el mundo 📢',               text_option_b: 'Disfruto el último día en secreto 🎉' },
    { question_text: '¿Qué preferirías mientras duermes?',                  text_option_a: 'Ver tu futuro en sueños 🌙',                    text_option_b: 'Revivir tus mejores momentos 💭' },
    { question_text: '¿Qué harías si descubres que eres adoptado?',         text_option_a: 'Buscar a mis padres biológicos 🔍',              text_option_b: 'No cambiaría nada, es mi familia 🏡' },
    { question_text: '¿Cuál es el peor final posible para ti?',             text_option_a: 'Morir sin haber amado de verdad 💔',            text_option_b: 'Haber amado y perderlo todo ❤️‍🩹' },
    { question_text: 'Si pudieras vivir solo una experiencia más, ¿cuál?',  text_option_a: 'El mejor momento ya vivido 🌟',                 text_option_b: 'Un futuro que aún no has vivido 🌈' },
    { question_text: '¿Qué elegirías si solo puedes tener uno?',            text_option_a: 'Ser muy inteligente pero solitario 🧠',         text_option_b: 'Ser muy querido pero mediocre 🤗' },
    { question_text: 'Si descubres un fraude en tu empresa, ¿qué haces?',   text_option_a: 'Lo denuncio aunque pierda el trabajo ⚖️',      text_option_b: 'Lo ignoro y me protejo 🤐' },
    { question_text: '¿Qué sacrificarías por la fama?',                     text_option_a: 'Tu privacidad total 📸',                        text_option_b: 'Tus relaciones íntimas 💔' },
    { question_text: '¿Verías todos los pensamientos de tu pareja?',        text_option_a: 'Sí, necesito saberlo todo 👁️',                 text_option_b: 'No, prefiero la incertidumbre 🙈' },
    { question_text: '¿Qué es peor?',                                       text_option_a: 'Que alguien te mienta sabiendo que duele 🗡️',   text_option_b: 'Que alguien te oculte algo por protegerte 🛡️' },
    { question_text: 'Si tu mejor amigo/a comete un delito, ¿qué haces?',   text_option_a: 'Lo encubro, es mi amigo/a 🤫',                  text_option_b: 'Lo denuncio, es lo correcto ⚖️' },
    { question_text: '¿Qué preferirías perder?',                            text_option_a: 'Cinco años de recuerdos felices 💭',            text_option_b: 'Cinco años de tu futuro ⏳' },
    { question_text: 'Si pudieras vivir eternamente, ¿lo harías?',          text_option_a: 'Sí, quiero ver todo el futuro 🌌',              text_option_b: 'No, la vida vale por su finitud ⏰' },
    { question_text: 'Si el mundo es una simulación, ¿qué harías?',         text_option_a: 'Viviría igual, es lo que hay 🤷',               text_option_b: 'Lo aprovecharía sin límites 🎮' },
    { question_text: '¿Qué prefieres: verdad o felicidad?',                 text_option_a: 'La verdad siempre, aunque duela 💊',            text_option_b: 'La felicidad, aunque sea ilusión 🌈' },
    { question_text: '¿Qué sería peor para ti?',                            text_option_a: 'Haber tenido lo que amas y perderlo 💔',        text_option_b: 'Nunca haber arriesgado por miedo 🔒' },
    { question_text: '¿Cuál es tu precio?',                                 text_option_a: 'El más rico pero nadie te conoce 💎',           text_option_b: 'El más conocido pero siempre en deuda 📸' },
    { question_text: '¿Qué preferirías saber antes de morir?',              text_option_a: 'Si hay algo después 🌌',                        text_option_b: 'Si tu vida tuvo impacto real 🌱' },
    { question_text: '¿Cuál sería el peor tipo de traición?',               text_option_a: 'Que te roben una oportunidad por envidia 😤',   text_option_b: 'Que te fallen cuando más lo necesitas 😢' },
    { question_text: '¿Qué sería más difícil de aceptar?',                  text_option_a: 'Que tu mayor logro fue fruto de la suerte 🎰',  text_option_b: 'Que tus mejores años ya pasaron 📅' },
    { question_text: '¿Qué es más valiente?',                               text_option_a: 'Decir lo que piensas sin filtros 🗣️',          text_option_b: 'Callarte cuando el otro no puede escucharlo 🤐' },
    { question_text: '¿Qué tipo de poder preferirías?',                     text_option_a: 'Económico ilimitado 💰',                        text_option_b: 'Influencia sobre millones 📢' },
    { question_text: '¿Qué preferirías haber sido?',                        text_option_a: 'Alguien que cambió el mundo pero fue olvidado 🌍', text_option_b: 'Alguien amado en un círculo pequeño 💞' },
    { question_text: '¿Qué te pesaría más en tu lecho de muerte?',          text_option_a: 'No haber amado lo suficiente 💔',               text_option_b: 'No haber conseguido lo que te propusiste ❌' },
    { question_text: '¿10 años más de vida a cambio de perder un sentido?', text_option_a: 'Sí, acepto perder el oído 🙉',                  text_option_b: 'No, sin mis sentidos no es vida 🚫' },
    { question_text: '¿Qué sería más destructivo para ti?',                 text_option_a: 'Que tu historia de amor fue mentira 💔',        text_option_b: 'Que tu mejor amigo nunca te quiso 🥀' },
    { question_text: '¿Qué preferirías que perdurara de ti?',               text_option_a: 'Tus obras o logros 🏛️',                        text_option_b: 'El amor de quienes te conocieron 💙' },
    { question_text: 'Si puedes elegir tu muerte, ¿qué prefieres?',         text_option_a: 'Rápida e inesperada ⚡',                        text_option_b: 'Lenta pero con tiempo para despedirte 🕯️' },
    { question_text: '¿Si pudieras cambiar una decisión pasada?',           text_option_a: 'La que te causó más dolor 😭',                  text_option_b: 'La que cambió el rumbo de tu vida 🔀' },
    { question_text: '¿Si el fin justifica los medios, hasta dónde?',       text_option_a: 'Mentiría, pero no haría daño físico 🤥',        text_option_b: 'No cruzo ninguna línea ética ❌' },
    { question_text: '¿Qué memoria guardarías si solo puedes una?',         text_option_a: 'La infancia 🧒',                                text_option_b: 'Un momento del futuro que aún no has vivido 🔮' },
    { question_text: '¿Qué te pesa más?',                                   text_option_a: 'No haber dicho «te quiero» a tiempo 💌',        text_option_b: 'No haber dicho «no» antes ✋' },
    { question_text: 'Si descubres que tu empresa causa daño ambiental...',  text_option_a: 'Lo denuncio aunque pierda el trabajo 🌍',       text_option_b: 'Trabajo desde dentro para cambiarlo 🔄' },
    { question_text: '¿Qué elegirías para tu hijo/a?',                      text_option_a: 'Que fracase pero aprenda 📉',                   text_option_b: 'Que triunfe sin haberlo merecido 🏆' },
    { question_text: '¿Qué es más valioso al final de todo?',               text_option_a: 'Lo que construiste solo 🏗️',                   text_option_b: 'Lo que construiste con otros 🫂' },
    { question_text: '¿Cuál sería la peor soledad?',                        text_option_a: 'Estar rodeado de gente que no te conoce 👥',    text_option_b: 'Estar solo sabiendo que nadie te espera 🌑' },
  ],
}

export function pickRandom(bank: QuestionPreset[], n: number): QuestionPreset[] {
  const shuffled = [...bank]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled.slice(0, n)
}
